apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongod
  name: mongo-nodeport-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32017
  selector:
    app: mongod
  type: NodePort
status:
  loadBalancer: {}