apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
  labels:
    pv: pv-01
spec:
  capacity:
    storage: 10G
  accessModes:
  - ReadWriteOnce
  local:
    path: /nfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [worker1]}