version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: eagle
      MONGO_INITDB_ROOT_PASSWORD: k5b201eagle

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27100:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://eagle:k5b201eagle@k5b201.p.ssafy.io:27017/
    depends_on:
      - mongo
