apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  ports:
    - nodePort: 30803
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
    prometheus: k8s
  type: NodePort
